### ISSUE TITLE
Erlang support

### ISSUE THREAD

**Issue by adelarsq** [ityonemo/zigler#181]
Is it possible to use Zigler with Erlang?

I'm interested to use with Gleam, but appears that need some support for Erlang to work https://github.com/gleam-lang/suggestions/issues/73.

**Comment by ityonemo** [comment]
The answer is complicated.
1) I *think* you can use an Zigler module compiled in elixir, in erlang.  Zigler is designed to be a "runtime: false" dependency.  If you would like to try it and report back, that would be appreciated!
2) Compilation of Zigler without elixir is "basically impossible".  There's a TON of elixir-specific metaprogramming involved to get Zig to be written inline in elixir.
3) I don't want to leave erlang totally in the dust with zig, in theory there should be a way to use parse transforms to get inline zig into erlang, possibly using some modules from Zigler as assistance, but it's a little bit out of my personal abilities.  PRs welcome.

**Comment by michal-escola** [comment]
> Thanks @ityonemo
> 
> 1. I will try this approach
> 2. Makes sense
> 3. Would be nice
> 
> Right now I don't have so much time to invest on this, but it's something that I really want to make work, since Gleam and Zig appears to be a nice fit. So I plan to help on Gleam side and be back on this when understand correctly the process. Then I will be back on next weeks on this issue.

Did you solve it? I am also interested to use Zig in a pure Erlang.

**Comment by adelarsq** [comment]
@michal-escola No. I still didn't have time to see in depth. It's more complex that I was thinking at first, but I still didn't give up.

**Comment by ityonemo** [comment]
erlang support coming in 0.10.x release
