### ISSUE TITLE
test that beam.allocator works for something with alignment not 8

### ISSUE THREAD

**Issue by ityonemo** [ityonemo/zigler#210]

**Comment by LemonBoy** [comment]
`std.heap` exports a few functions to stress-test the allocator impls:

* `testAllocator`
* `testAllocatorAligned`
* `testAllocatorLargeAlignment`
* `testAllocatorAlignedShrink`

If your allocators pass the tests it's very likely for them to be correct.

**Comment by ityonemo** [comment]
wow awesome, thank you very much!

**Comment by ityonemo** [comment]
fantastic.  I've found an elusive segfault already.

**Comment by ityonemo** [comment]
@LemonBoy thank you!  I found my error EXTREMELY quickly thanks to the testAllocator code.
