### ISSUE TITLE
avoid Mojito as a dependency

### ISSUE THREAD

**Issue by dch** [ityonemo/zigler#212]
It's possible to drop Mojito and just use native httpc directly. This is 1 less dependency which can easily get in the way of a normal production app.  Would this be reasonable? I can PR it.

```elixir
base_url = "https://ziglang.org/"
# choose either an official release or a yolo tarball
# zig_tarball = "download/0.7.0/zig-0.7.0.tar.xz"
zig_tarball = builds/zig-0.7.0+4fd27719b.tar.xz"
Application.ensure_all_started :inets            
Application.ensure_all_started :ssl     
{:ok, {{_version, 200, _reason}, _headers, zig_src}} = :httpc.request(baseurl <> zig_tarball)
File.write!("zig.txz", zig_src)
```

It's also possible to add TLS peer verification, or use a `sha512` or something of the source tarball.

**Comment by ityonemo** [comment]
I'll accept a pr switching it out, but the readme suggests to use zigler as runtime: false dependency so it should not be available at runtime.  Also I thought httpc was going to be deprecated from otp.

**Comment by ityonemo** [comment]
Going to close this out since mojito should not be present at runtime, but still open to a pr.
