### ISSUE TITLE
Missing arm-features.h when compiling with Nerves

### ISSUE THREAD

**Issue by fhunleth** [ityonemo/zigler#232]
In a test project for the Raspberry Pi 3, I received the following error:

```
** (CompileError)  this zig compiler warning hasn't been incorporated into the parser.
Please file a report at:
https://github.com/ityonemo/zigler/issues
error(compilation): clang failed with stderr: In file included from /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/arm/crti.S:44:
In file included from /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/unix/sysv/linux/arm/sysdep.h:25:
In file included from /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/unix/arm/sysdep.h:19:
/home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/arm/sysdep.h:25:11: fatal error: 'arm-features.h' file not found

error(compilation): /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/arm/crti.S:1:1: unable to build C object: clang exited with code 1
```

`arm-features.h` is missing from https://github.com/ziglang/zig/tree/master/lib/libc/glibc/sysdeps/arm. 

## Debug attempt 1

Out of curiousity, I copied https://github.com/bminor/glibc/blob/master/sysdeps/arm/arm-features.h to my local sysdeps directory to see what would happen. I got past that one error, but then hit:

```
/home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/unix/sysv/linux/single-thread.h:48:6: error: function-like macro 'IS_IN' is not defined
```

To fix that error, I added

```
#include <libc-symbols.h> 
```

to `zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/arm/crtn.S`. In theory, `libc-symbols.h` is supposed to be automatically included to all glibc compiled files.

My next error is:

```
error(compilation): clang failed with stderr: In file included from /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/io/mknod.c:36:
In file included from /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/include/sys/types.h:1:
In file included from /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/posix/sys/types.h:227:
In file included from /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/nptl/bits/pthreadtypes.h:23:
In file included from /home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/nptl/bits/thread-shared-types.h:87:
/home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/include/arm-linux-gnueabihf/bits/struct_rwlock.h:29:8: error: redefinition of '__pthread_rwlock_arch_t'
/home/fhunleth/nerves/zigler/zig/zig-linux-x86_64-0.7.1/lib/libc/glibc/sysdeps/arm/nptl/bits/pthreadtypes-arch.h:43:8: note: previous definition is here
```

This was an interesting error, since the comment in `struct_rwlock.h` says that "architectures can redefine it (the struct)
to add arch-specific extensions" so this seems like it is intentionally redefined. I don't understand that. For lulz, I commented out
the struct so that it would no longer be redefined. I figured that I'd worry about rwlocks later...

Now I'm getting a stream of errors that look like this:

```
/home/fhunleth/.cache/zig/o/4e1a4f0d8bc6cdba196ff46077483126/c.s:2:18: error: expected STT_<TYPE_IN_UPPER_CASE>, '#<type>', '%<type>' or "<type>"
.type _Exit_2_4, @function;
                 ^
/home/fhunleth/.cache/zig/o/4e1a4f0d8bc6cdba196ff46077483126/c.s:7:28: error: expected STT_<TYPE_IN_UPPER_CASE>, '#<type>', '%<type>' or "<type>"
.type _IO_2_1_stderr__2_4, @function;
                           ^
```

It could be that I brought this on myself with my hacks, but I didn't understand these.

## Debug attempt 2

I tried non-ARM targets. I had to modify Zigler to pass the right build options, but my end goal is to make it easy for Zigler to get the right options from Nerves. In other words, I'm not worried about hacking target selection into Zigler right now. Here are the results:

* Crosscompiling for x86_64-linux-gnu and x86_64-linux-musl both seem to work
* i386-linux-gnu seems to work
* mipsel-linux-gnu doesn't work. I get a "key not found" error

## Debug attempt 3

I also tried downgrading zig to 0.7.0 and 0.6.0 to see if I could find a usable version. Neither of those worked either. I can downgrade to 0.3.1 and make progress, but it looks like you've put in a lot of work to Zigler since 0.3.1. If I can help get Zigler 0.7.1 working with Nerves, let me know. 

## Final notes

I'm pretty sure that all of these leads to some upstream `zig` issue, but I'm not quite sure how to package a bug report to make it easy for them to debug. It seems like the part that breaks is the `--library c` since `zig` appears to crosscompile other non-zigler files without that. 

Hopefully something that I wrote above makes sense and is helpful.

**Comment by ityonemo** [comment]
- I encountered the "arm-features.h" missing and wound up with the IS_IN error and gave up there.  Thanks for showing me a way forward on that.   The struct_rwlock.h error is something that I also encountered before, and there is a patch for that in zigler 0.3.2 that would be easy to resurrect as an experiment to get that working.

- I ALSO encountered the @function problem, when trying to use linux-musl instead of linux-gnu, so it's not you!

- When I take a swing at this tonight I'll try removing libc.  I seem to recall that there is some erlang system dependency on that, but I could be imagining things!

- So I think part of what brought this on was switching from using the zig command line to build the library over to using build.zig to build the library; I think I'm not exactly matching the build.zig parameters correctly to the incantation that I was using, so I'll also spend some time doing a deeper dive on that!  I wonder if there's a way for me to probe the command line equivalent;  I *believe* that build.zig works by literally constructing a zig command line.

**Comment by fhunleth** [comment]
> I believe that build.zig works by literally constructing a zig command line.

That's the feeling that I got too. When I was debugging, I was manually running the zig command line and tweaking it. Then I was figuring out how whatever I did was represented in the build.zig.

Regarding removing libc, did you get a chance to try that? If libc was required, I was thinking of taking a pass at making a small example program that could be posted to the zig issues for help. Unless you had a better idea on how to proceed, that is.

Thanks again!!!

**Comment by ityonemo** [comment]
got blocked at work on a bit of stuff so I poked around a bit and figured out how to make it so that libc is not necessary.  The only reason why it wants libc because the erlang headers for example want types.h, but all of the critical stuff is not libc-dependent.  Either tonight or tomorrow I should have some time to try and make this solution generalizable.

**Comment by ityonemo** [comment]
If this gets cleared, I think, it should be possible to deploy content that doesn't use libc onto rpi seamlessly; but I should also double check that you can, for example, use malloc in both host and try (again) to get it working in target mode.

**Comment by fhunleth** [comment]
That would be great. Assuming it works, the Raspberry Pi 3 should be good. The Raspberry Pi Zero will need `-mcpu arm1176jzf_s` added to the commandline or the equivalent to the `build.zig`, but Nerves will have to pass that in since I don't know how that could be inferred. Anyway, that's a part that I can handle.

**Comment by ityonemo** [comment]
wip:  https://github.com/ityonemo/zigler/tree/nerves-0.7.1

- now pulls only a minimal set of header files required for erlang's c lib.
- requires link_libc option for things that really need to link libc.
not tested on rpi, yet (will probably do tomorrow)
not tested on mac
not tested on freebsd
very not tested on windows

**Comment by ityonemo** [comment]
current status - It compiles, but I'm unable to run `nerves firmware.burn`.  I'm not sure if my sd-mmc drive on my system76 is wonky, but also the sd-mmc card I have looks like it's bent, so I am going to need to retry it.  @fhunleth is there a usb-sdmmc adapter that you recommend in the case that this internal slot is unrecognized?

**Comment by fhunleth** [comment]
I might be able to try later tonight. 

As for MicroSD card readers, they all seem to basically work for me. Some wear out or break faster than others. I currently like the Kingston ones like https://www.amazon.com/Kingston-MobileLite-Plus-microSDHC-Reader/dp/B085P5FDXQ, but unless you're going to really use it a lot, I'd probably just get whatever is most convenient.

**Comment by ityonemo** [comment]
tested on rpi3 with https://github.com/ityonemo/zigler/pull/235, going to bump version on hex.pm to 0.7.2, with a provision to update to 0.7.3 if the other selections for the other platforms seem sane.

**Comment by fhunleth** [comment]
Great! I think Zigler is good to go for Nerves. @mobileoverlord and I need to finalize how to pass specific processor information to Zigler to improve what you have right now. Since this currently only affects the original Raspberry Pi and the Pi Zero on the official Nerves supported list, I think that most people using Zig with Nerves will be ok. I'll post when we have something.

**Comment by ityonemo** [comment]
I forgot to mention - I believe there is already a hello_zig branch of nerves-examples which is what i used for testing.

**Comment by fhunleth** [comment]
Yes! I've been keeping it open to make @mobileoverlord and I finish off our part. And I've been locally trying it out in my testing. I originally didn't want to merge it since the RPi Zero didn't work and that's a really popular board for Nerves. However, I'm feeling guilty for leaving the PR open so long and zig is too cool, so if Justin and I can't get something in soon, I'm going to merge it with a note on what platforms are supported.

**Comment by ityonemo** [comment]
looks like this is settled, so I am going to close!
