### ISSUE TITLE
verify that all the standard beam types are active.

### ISSUE THREAD

**Issue by ityonemo** [ityonemo/zigler#25]

**Comment by ityonemo** [comment]
Duplicate of #11

**Comment by ityonemo** [comment]
from: http://erlang.org/doc/reference_manual/data_types.html
[] char
[] integer
[] float
[] atom
[] binary
[] reference
-- not going to do funs
[] pid
[] tuple
[] map
[] list
[] charlist
[] intlist
[] floatlist
[] boolean

**Comment by ityonemo** [comment]
rejigger the function header parsing tests to be in a single module (to decrease compile time) and make sure they all trampoline to the corresponding beam functions instead of running them internally as a part of the code.

- [ ] char
- [ ] integer
- [ ] float
- [ ] atom
- [ ] binary
- [ ] pid
- [ ] tuple
- [ ] list
- [ ] charlist
- [ ] intlist
- [ ] floatlist
- [ ] boolean

**Comment by ityonemo** [comment]
rejigger egress tests.

- [ ] char
- [ ] integer
- [ ] float
- [ ] atom
- [ ] binary
- [ ] pid
- [ ] list
- [ ] intlist
- [ ] floatlist
- [ ] boolean

**Comment by heri16** [comment]
Shall we have this as a table in the Readme?

**Comment by ityonemo** [comment]
Yes, please.  Can you make a PR?  This will be helpful as I will start the bump to 0.9.0 in 1 week

**Comment by heri16** [comment]
Would elixir maps correspond to zig anonymous structs?

**Comment by ityonemo** [comment]
No, I think at best I would have to convert them to zig hashmaps backed by the beam allocator.  I do have an idea that it should be possible to convert non-anonymous zig structs into elixir structs.

**Comment by ityonemo** [comment]
Tuples could probably be mapped to zig tuples in a sane fashion.
