### ISSUE TITLE
Read from Console / STDIN ??

### ISSUE THREAD

**Issue by andyl** [ityonemo/zigler#293]
I'm writing an Elixir CLI and it would be handy to have a `getch` or `readline` function.  I did a simple test with Zig, wondering if I could read STDIN characters from the console.

```zig
~Z"""
  const stdout = std.io.getStdOut().writer(); 
  const stdin = std.io.getStdIn().reader();
  
  /// nif: console_test/0 
  fn console_test() !void {
    var buf: [100]u8 = undefined; 
    try stdout.print("ENTER STRING > ", .{}); 
    var num = try stdin.read(buf[0..]); 
    try stdout.print("NUMBYTES {}\n", .{num}); 
    try stdout.print("String ({s})\n", .{buf[0..num]}); 
  }
"""
```

This code works as a standalone ZIG executable (using `zig build-exe ...`) but not as a Zigler Nif.  Zigler's `threaded`, `dirty_io` and `yielding` options all failed for me.

Is there any way to use Zigler to read characters from the console?

**Comment by ityonemo** [comment]
I honestly don't know, but I don't recommend it -- for cli interactions it's probably better to use erlang's IO, because it will have possession of the stdin file descriptor

**Comment by andyl** [comment]
ok thanks!
