### ISSUE TITLE
Upgrade to use zig 9.1

### ISSUE THREAD

**Issue by jeremyowensboggs** [ityonemo/zigler#297]
Upgrade zigler to use zig 9.1

There are some significant challenges here.
No unused arguments or locals
Change to the allocator
Change to usingnamespace

https://ziglang.org/download/0.9.0/release-notes.html#Language-Changes

**Comment by jeremyowensboggs** [comment]
https://github.com/jeremyowensboggs/zigler/tree/0.9.0-development work in progress
The biggest hassle so far has been the tamp down of unused args/variables/captures.

Allocgate https://pithlessly.github.io/allocgate.html may still be an issue to some degree.
The tests at mix test ./test/integration/strategies/yielding_nif_test.exs seem to indicate that
the memory might not be beam controlled?

What is still outstanding test wise:
Doesn't compile
 mix test ./test/integration/zig_test/import_test.exs - This is from the change to usingnamespace, probably just needs the test removed.
 mix test ./test/integration/zig_test/zig_test.exs
 
Seg faults (on a mac at least)
 mix test ./test/integration/error_test.exs
 mix test ./test/integration/documentation/resource_test.exs
mix test ./test/integration/documentation/nifs_test.exs

Failing test
 mix test ./test/integration/strategies/yielding_nif_test.exs

**Comment by jeremyowensboggs** [comment]
https://github.com/ityonemo/zigler/pull/298

**Comment by ityonemo** [comment]
remaining tasks to close

- [ ] document new C++ features
- [ ] document new library linking features
- [ ] double check mutex and gpa impls
- [ ] changelog + special thanks
