### ISSUE TITLE
`no nifs found` compilation error when using Zig but not including NIFs

### ISSUE THREAD

**Issue by crertel** [ityonemo/zigler#334]
Hello!

I don't know how much of a bug this is, but right now I'm getting:

```
== Compilation error in file lib/backend.ex ==
** (CompileError) lib/backend.ex: no nifs found in the module Elixir.SimpleAudio.Backend
    (zigler 0.9.1) expanding macro: Zig.Compiler.__before_compile__/1
    lib/backend.ex:1: SimpleAudio.Backend (module)
```

This is caused by a module that (right now) looks like this:

```elixir
defmodule SimpleAudio.Backend do
  use Zig

  @moduledoc """
  The low-level backend, in Zig, for simple audio.
  """
end
```

Now, this is a totally fair error--I don't have any Zig in there yet!

But, I'd be curious if this would be better as a warning or something that wouldn't block compilation. What do you think?

**Comment by ityonemo** [comment]
I think that's reasonable!

**Comment by ityonemo** [comment]
this warning is no longer present.
