### ISSUE TITLE
Request to document nerves integration

### ISSUE THREAD

**Issue by samuelventura** [ityonemo/zigler#337]
It would be great to have a clear view of the rules to map nerves provided environment vars (target, toolchain, etc...) to the zig -target option. It would help those that want to write zig based beam ports.

**Comment by ityonemo** [comment]
will do =D will arrive with 0.10.0 -- probably around 4th wk of november.

**Comment by ityonemo** [comment]
sorry for the delay.  It will be definitely done second week of may, since I will be giving a talk on it =D  There are a lot of very nice changes.

**Comment by ityonemo** [comment]
the process is actually now fully automatic.
