### ISSUE TITLE
Error building on Mac M1 Pro (arm64)

### ISSUE THREAD

**Issue by jjones310** [ityonemo/zigler#402]
I tried adding zigler to a fresh elixir project after creating using `mix new ...`

Below is the error output, including instruction to open an issue, so here I am :) 

Please let me know if there's any other info I can provide. This looks like a very cool project, thank you!

    mix deps.get
    Resolving Hex dependencies...
    Resolution completed in 0.015s
    Unchanged:
      earmark_parser 1.4.33
      ex_doc 0.29.0
      jason 1.4.1
      makeup 1.1.0
      makeup_elixir 0.16.1
      makeup_erlang 0.1.2
      nimble_parsec 1.3.1
      zigler 0.9.1
    All dependencies are up to date
    
    iex -S mix
    Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
    
    Compiling 1 file (.ex)
    
    21:26:56.722 [debug] compiling nif for module Roaring in path /var/folders/_b/yypb1v3s5pg0w6dknt1tpv9h0000gq/T/.zigler_compiler/dev/Elixir.Roaring
    
    21:26:56.861 [debug] wrote build.zig to /var/folders/_b/yypb1v3s5pg0w6dknt1tpv9h0000gq/T/.zigler_compiler/dev/Elixir.Roaring/build.zig
    
    == Compilation error in file lib/roaring.ex ==
    ** (CompileError)  this zig compiler warning hasn't been incorporated into the parser.
    Please file a report at:
    https://github.com/ityonemo/zigler/issues
    thread 1085492 panic: Darwin is handled separately via std.zig.system.darwin module
    Unable to dump stack trace: debug info stripped

    (zigler 0.9.1) lib/zig/parser/error.ex:60: Zig.Parser.Error.parse/2
    (zigler 0.9.1) lib/zig/command.ex:35: Zig.Command.compile/2
    (zigler 0.9.1) lib/zig/compiler.ex:102: Zig.Compiler.compilation/2
    (zigler 0.9.1) expanding macro: Zig.Compiler.__before_compile__/1
    lib/roaring.ex:1: Roaring (module)

**Comment by ityonemo** [comment]
Can you try with the 0.10.0 branch here on github?  This will be releasing on hex.pm 0.10.1 version in the next few days (I'm wrapping up documentation)

**Comment by jjones310** [comment]
I tried on using the 0.10.0 branch. I've tried the below on macos and ubuntu linux, same result. At first I received the below error. It looks like it wasn't downloading zig.

      Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
      
      Compiling 1 file (.ex)
      
      == Compilation error in file lib/roaring.ex ==
      ** (ErlangError) Erlang error: :enoent:
      
        * 1st argument: invalid port name
      
          :erlang.open_port({:spawn_executable, '/home/jason/roaring/deps/zigler/zig/zig-linux-x86_64-0.10.1/zig'}, [:use_stdio, :exit_status, :binary, :hide, {:args, ["fmt", "/tmp/Elixir.Roaring/build.zig"]}])
          (elixir 1.14.5) lib/system.ex:1071: System.do_cmd/3
          (zigler 0.10.1) lib/zig/command.ex:23: Zig.Command.run_zig/2
          (zigler 0.10.1) lib/zig/builder.ex:33: Zig.Builder.build/2
          (zigler 0.10.1) lib/zig/compiler.ex:69: Zig.Compiler.compile/4
          (zigler 0.10.1) expanding macro: Zig.Compiler.__before_compile__/1
          lib/roaring.ex:1: Roaring (module)

Next, I manually downloaded zig at the location where the `.open_port` call was expecting. This removed the `open_port` error, but then I saw this log message:

    Compiling 1 file (.ex)
    
    14:46:13.740 [debug] wrote build.zig to /tmp/Elixir.Roaring/build.zig
    
    14:46:15.012 [debug] wrote module.zig to /tmp/Elixir.Roaring/module.zig
    
    14:46:15.039 [debug] built library at /home/jason/roaring/_build/dev/lib/roaring/priv/lib/Elixir.Roaring.so
    
    14:46:15.054 [info] module Roaring does not compile its nifs
    Generated roaring app
    
Here is my module. Log message mentions my module `does not compile its nifs`. Is the `use Zig, otp_app: :roaring` correct in this case?

    defmodule Roaring do
      use Zig, otp_app: :roaring
      ~Z"""
      /// nif: example_fun/2
      fn example_fun(value1: f64, value2: f64) bool {
        return value1 > value2;
      }
      """
    end

Here's my test repo:
https://github.com/jjones310/zigler-macos

Thank you for looking into this. Let me know if there's anything else I can test.

**Comment by ityonemo** [comment]
Thanks for the bug report!  I'm doing a macros run tomorrow and will let you know how it goes

**Comment by ityonemo** [comment]
ah yes.  My fault, I need to document this =D

you forgot to run `mix zig.get`

Also, the API has changed, now your sigil z should look like:

  ~Z"""
  pub fn example_fun(value1: f64, value2: f64) bool {
    return value1 > value2;
  }
  """
  
where `pub` signifies that it should be hoisted into the module.

**Comment by jjones310** [comment]
oh I see, thank you!

Everything is working perfect now.

Good luck on the 0.10 release!
