### ISSUE TITLE
error downloading zig version 0.9.1

### ISSUE THREAD

**Issue by jjones310** [ityonemo/zigler#403]
Running into the below issue when trying to compile project after adding zigler to deps. Additionally, I first added 
`{:ex_doc, "~> 0.28.0"}`, to get past the `key :function_groups not found` issue.

My environment is WSL 2 (Windows Subsystem for Linux) Ubuntu Linux.

Please let me know if there's any other info that I can provide. Thanks!

     iex -S mix
    Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
    
    ==> ex_doc
    Compiling 25 files (.ex)
    Generated ex_doc app
    ==> zigler
    Compiling 27 files (.ex)
    warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
      lib/zig/command.ex:66: Zig.Command (module)
    
    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
      lib/zig/command.ex:143: Zig.Command.windows_warn/0
    
    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
      lib/zig/parser.ex:274: Zig.Parser.warn_on_bad_declaration/5
    
    Generated zigler app
    ==> roaring
    Compiling 1 file (.ex)
    
    22:36:32.795 [info] downloading zig version 0.9.1 (https://ziglang.org/download/0.9.1/zig-linux-x86_64-0.9.1.tar.xz) and caching in /home/jason/projects/roaring/deps/zigler/zig.
    
    == Compilation error in file lib/roaring.ex ==
    ** (RuntimeError) failed to download the appropriate zig archive.
        (zigler 0.9.1) lib/zig/command.ex:226: Zig.Command.download_zig_archive/3
        (zigler 0.9.1) lib/zig/command.ex:175: Zig.Command.fetch/1
        (zigler 0.9.1) lib/zig/compiler.ex:127: Zig.Compiler.zig_location/3
        (zigler 0.9.1) expanding macro: Zig.Compiler.__before_compile__/1
        lib/roaring.ex:1: Roaring (module)

**Comment by ityonemo** [comment]
this is because 0.9.1 has a broken exdoc dependency.  This is resolved in 0.10.0 by breaking out zig_doc as its own dependency that is strictly optional for projects that use it.
